trigger:
- main

pool:
  name: self-hosted-pool

stages:

- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        docker build -t sarashcr.azurecr.io/myapp:latest .
        docker push sarashcr.azurecr.io/myapp:latest

- stage: Deploy_Dev
  jobs:
  - job: Deploy
    steps:
    - script: |
        kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f dev-deploy.yaml

- stage: Approval
  jobs:
  - job: Wait
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: "Approve deployment to PROD"

- stage: Deploy_Prod
  jobs:
  - job: Deploy
    steps:
    - script: |
        kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f prod-deploy.yaml