trigger:
- main

pool:
  name: self-hosted-pool

variables:
  ACR_NAME: sarashcr
  AKS_NAME: aks
  RG: sarash-devops

stages:

# ---------------- BUILD IMAGE ----------------
- stage: Build_Image
  displayName: "Build & Push Docker Image to ACR"
  jobs:
  - job: Build
    displayName: "Build and Push Image"
    steps:
    - script: |
        az login --identity
        az acr login --name $ACR_NAME

        docker build -t $ACR_NAME.azurecr.io/myapp:$(Build.BuildId) .
        docker push $ACR_NAME.azurecr.io/myapp:$(Build.BuildId)
      displayName: "Docker Build & Push"

# ---------------- DEPLOY TO DEV (WITH APPROVAL) ----------------
- stage: Deploy_Dev
  displayName: "Deploy to Dev"
  dependsOn: Build_Image
  jobs:
  - deployment: DeployDev
    displayName: "Deploy to Dev Namespace"
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              az login --identity
              az aks get-credentials --name $AKS_NAME --resource-group $RG --overwrite-existing

              kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -

              kubectl apply -f $(System.DefaultWorkingDirectory)/k8s/dev.yaml
              kubectl apply -f $(System.DefaultWorkingDirectory)/k8s/dev-ingress.yaml

              kubectl set image deployment/myapp \
                myapp=$ACR_NAME.azurecr.io/myapp:$(Build.BuildId) \
                -n dev
            displayName: "Deploy to Dev"

# ---------------- DEPLOY TO PROD (WITH APPROVAL) ----------------
- stage: Deploy_Prod
  displayName: "Deploy to Production"
  dependsOn: Deploy_Dev
  jobs:
  - deployment: DeployProd
    displayName: "Deploy to Prod Namespace"
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              az login --identity
              az aks get-credentials --name $AKS_NAME --resource-group $RG --overwrite-existing

              kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -

              kubectl apply -f $(System.DefaultWorkingDirectory)/k8s/prod.yaml
              kubectl apply -f $(System.DefaultWorkingDirectory)/k8s/prod-ingress.yaml

              kubectl set image deployment/myapp \
                myapp=$ACR_NAME.azurecr.io/myapp:$(Build.BuildId) \
                -n prod
            displayName: "Deploy to Production"