apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sarashcr.azurecr.io/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

        # 🔥 ADD THIS BLOCK
        env:
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_CONN
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80